# Generated by Django 5.1.4 on 2025-01-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='coluna',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maquina',
            name='linha',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
