# Generated by Django 5.1.4 on 2025-01-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_maquina_coluna_maquina_linha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=500)),
                ('resolvido', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='maquina',
            name='coluna',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='linha',
            field=models.IntegerField(default=0),
        ),
    ]
