# Generated by Django 5.1.4 on 2025-01-13 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_problema_alter_maquina_coluna_alter_maquina_linha'),
    ]

    operations = [
        migrations.AddField(
            model_name='problema',
            name='maquina',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='controle.maquina'),
            preserve_default=False,
        ),
    ]
